### ISSUE TITLE
Prikaz slika

### ISSUE THREAD

**Issue by invalidSwitch** [davidfdgh/Travel-Photo-Diary#1]
Postoji problem sa prikazom slika na naslovnoj strani. Bice da nije dozvoljen javni pristup google slikama.

Na dnu strane, gde su linkovi za soc. mreze nije prikazan GitHub-ov octocat.

**Comment by davidfdgh** [comment]
Smanjio sam rezoluciju slika, tako da sam ih upload-ovao na Git. Bilo je problema za ucitavanje back-ground slike, iako je link bio korigovan. Tek sada uspeo ucitati.

Git ikonicu nije ucitao, iz banalne greske. Fajl nazvan "Git.png", a u kodu pozvan "git.png"

Hvala na kritici, i moze slobodno neka ideja sta jos dodati.
